export enum TransactionTypes {
  SERVICES = "Servicios",
  HOUSING = "Vivienda",
  TRANSPORT = "Transporte",
  FOOD = "Alimentación",
  HEALTH = "Salud",
  EDUCATION = "Educación",
  SAVINGS = "Ahorro",
  INVESTMENTS = "Inversiones",
  ENTERTAINMENT_AND_LEISURE = "Entretenimiento y ocio",
  DEBTS_AND_CREDITS = "Deudas y créditos",
  CLOTHING_AND_SHOES = "Ropa y calzado",
  INSURANCE = "Seguros",
  DONATIONS_AND_AIDS = "Donaciones y ayudas",
  TAXES = "Impuestos",
  PERSONAL_EXPENSES = "Gastos personales",
}
